apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      name: node-pod
      labels:
         app: test-app
    spec:
     containers:
      - name: node-container
        image: 900143203254.dkr.ecr.ap-south-1.amazonaws.com/eks-images:node-c36e7eca
        ports:
         - containerPort: 8080
