apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
          app: test-app
spec:
  containers:
  - name: node-container
    image: 900143203254.dkr.ecr.ap-south-1.amazonaws.com/eks-images:node-c36e7eca
    ports:
    - containerPort: 8080
