apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
          app: test-app
spec:
  containers:
  - name: node-container
    image: rajat16/eks-demo:node-code
    ports:
    - containerPort: 8080
