apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-service-label
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30004
  selector:
    app: test-app
  type: NodePort
